# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.3"
manifest_format = "2.0"
project_hash = "1332e7fcddc7b27696dfc03a673067f7bca06d97"

[[deps.TAUProfile]]
path = "."
uuid = "33839dc5-b46e-4b71-8209-33fe77383070"
version = "0.2.0"
