include ../../../include/Makefile
include ../Makefile

INSTALLDEST = $(TAU_PREFIX_INSTALL_DIR)/$(CONFIG_ARCH)/lib

install: tau_timeroutputs.jl
	mkdir -p $(INSTALLDEST)
	cp tau_timeroutputs.jl $(INSTALLDEST)/tau_timeroutputs.jl

clean:
