include ../../../Makefile.inc

SOURCES	= AbstractSyntax.java \
	  AbstractSyntaxTree.java \
	  Declaration.java \
	  DecList.java \
	  Directive.java \
	  DirectiveList.java \
	  Entity.java \
	  EntityList.java \
	  Field.java \
	  Group.java \
	  GroupList.java \
	  IncludeDec.java \
	  Instrumentation.java \
	  InstrumentationList.java \
	  ListManager.java \
	  Literal.java \
	  MultiStatement.java \
	  Operator.java \
	  OperatorStatement.java \
	  Statement.java \
	  StatementList.java \
	  SyntaxAttribute.java \
	  SyntaxElement.java \
	  SyntaxList.java

.PHONEY : default all clean clean-emacs

default : all

all : $(SOURCES)
	$(JAVAC) $(SOURCES)

clean :

