      PROGRAM EXAMPLE

      INTEGER I, LSUM, SUM

C!$OMP PARALLEL PRIVATE(NTHREADS, TID)
      SUM = 0

C!$OMP END PARALLEL
!$OMP PARALLEL PRIVATE(I, LSUM) REDUCTION(+:SUM)
      LSUM = 0

!$OMP DO
      DO I=1,20
         LSUM = LSUM + I
      ENDDO
!$OMP END DO

      WRITE(*,*) "local sum: ", LSUM
      SUM = SUM + LSUM
!$OMP END PARALLEL

      WRITE(*,*) "TOTAL SUM: ", SUM

      END
