name = "TAUJuliaExamples"
uuid = "226cbafb-4bcf-4889-81a1-5fb8ea187eae"
version = "0.1.0"
authors = ["Nicholas Chaimov <nchaimov@paratools.com>"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"

[compat]
CUDA = "5.9.6"
MPI = "0.20.23"
MPIPreferences = "0.1.11"
