"Usage: opari2 [OPTION] ... infile [outfile]\n"
"            \n"
"with following options and parameters:\n"
"\n"
"[--f77|--f90|--c|--c++]  [OPTIONAL] Specifies the programming language\n"
"                         of the input source file. This option is only\n"
"                         necessary if the automatic language detection\n"
"                         based on the input file suffix fails.\n"
"\n"
"[--nosrc]                [OPTIONAL] If specified, OPARI2 does not\n"
"                         generate #line constructs, which allow to\n"
"                         preserve the original source file and line\n"
"                         number information, in the transformation\n"
"                         process. This option might be necessary if\n"
"                         the OpenMP compiler does not understand #line\n"
"                         constructs.  The default is to generate #line\n"
"                         constructs.\n"
"\n"
"[--tpd]                  [OPTIONAL] Adds the clause 'copyin(<pomp_tpd>)'\n"
"                         to any parallel construct. This allows to\n"
"                         pass data from the creating thread to its\n"
"                         children. The variable is declared externally\n"
"                         in all files, so it needs to be defined by\n"
"                         the pomp library.\n"
"\n"
"[--disable constructs]   [OPTIONAL] Disable the instrumentation of\n"
"                         manually-annotated POMP regions or the\n"
"                         more fine-grained OpenMP constructs such as\n"
"                         !$OMP ATOMIC.  constructs is a comma\n"
"                         separated list of the constructs for which\n"
"                         the instrumentation should be disabled.\n"
"                         Accepted tokens are atomic, critical, master,\n"
"                         flush, single or locks (as well as sync to\n"
"                         disable all of them) or regions.\n"
"\n"
"[--task=                 Special treatment for the task directive\n"
"      abort|warn|remove] abort:  Stop instrumentation with an error\n"
"                                 message when encountering a task\n"
"                                 directive.\n"
"                         warn:   Resume but print a warning.\n"
"                         remove: Remove all task directives.\n"
"\n"
"[--untied=               Special treatment for the untied task attribute.\n"
"     abort|keep|no-warn] The default beavior is to remove the untied\n"
"                         attribute, thus making all tasks tied, and print\n"
"                         out a warning.\n"
"                         abort:   Stop instrumentation with an error\n"
"                                  message when encountering a task \n"
"                                  directive with the untied attribute.\n"
"                         keep:    Do not remove the untied attribute.\n"
"                         no-warn: Do not print out a warning.\n"
"\n"
"[--tpd-mangling          [OPTIONAL] If programming languages are mixed\n"
" gnu|intel|sun|pgi|      (C and Fortran), the <pomp_tpd> needs to use\n"
" ibm|cray]               the Fortran mangled name also in C files.\n"
"                         This option specifies to use the mangling\n"
"                         scheme of the gnu, intel, sun, pgi or ibm\n"
"                         compiler. The default is to use the mangling\n"
"                         scheme of the compiler used to build opari2.\n"
"\n"
"[--version]              [OPTIONAL] Prints version information.\n"
"\n"
"[--help]                 [OPTIONAL] Prints this help text.\n"
"\n"
"infile                   Input file name.\n"
"\n"
"[outfile]                [OPTIONAL] Output file name. If not\n"
"                         specified, opari2 uses the name\n"
"                          infile.mod.suffix if the input file is\n"
"                         called infile.suffix.\n"
"\n"
"Report bugs to <scorep-bugs@groups.tu-dresden.de>.\n"
