"Usage: otf2-print [OPTION]... ANCHORFILE \n"
"Print the content of all files of an OTF2 archive with the ANCHORFILE.\n"
"\n"
"  -A, --show-all           Print all output including definitions and anchor file.\n"
"  -G, --show-global-defs   Print all global definitions.\n"
"  -I, --show-info          Print information from the anchor file.\n"
"  -M, --show-mappings      Print mappings to global definitions.\n"
"  -C, --show-clock-offsets Print clock offsets to global timer.\n"
"  -L, --location LID       Limit output to location LID.\n"
"  -s, --step N             Step through output by steps of N events.\n"
"      --silent             Only validate trace and do not print any events.\n"
"      --time MIN MAX       Limit output to events within time interval.\n"
"  -d, --debug              Turn on debug mode.\n"
"  -V, --version            Print version information.\n"
"      --system-tree        Output system tree to dot-file.\n"
"  -h, --help               Print this help information.\n"
"\n"
"Report bugs to <scorep-bugs@groups.tu-dresden.de>\n"
"\n"
