"Usage: otf2-print [OPTION]... [--] ANCHORFILE\n"
"Print selected content of the OTF2 archive specified by ANCHORFILE.\n"
"\n"
"Options:\n"
"  -A, --show-all          print all output including definitions and anchor\n"
"                          file\n"
"  -G, --show-global-defs  print all global definitions\n"
"  -I, --show-info         print information from the anchor file\n"
"  -T, --show-thumbnails   print the headers from all thumbnails\n"
"  -M, --show-mappings     print mappings to global definitions\n"
"  -C, --show-clock-offsets\n"
"                          print clock offsets to global timer\n"
"      --timestamps=<FORMAT>\n"
"                          format of the timestamps. <FORMAT> is one of:\n"
"                           plain -  no formatting is done (default)\n"
"                           offset - timestamps are relative to the global offset\n"
"                                    (taken form the ClockProperties definition)\n"
"  -L, --location <LID>    limit output to location <LID>\n"
"  -s, --step <N>          step through output by steps of <N> events\n"
"      --time <MIN> <MAX>  limit output to events within time interval\n"
"      --system-tree       output system tree to dot-file\n"
"      --silent            only validate trace and do not print any events\n"
"      --unwind-calling-context\n"
"                          unwind the calling context for each calling context\n"
"                          event. Each calling context node is prefixed depending\n"
"                          on the unwind distance of the current event:\n"
"                           '?' - unwind distance is undefined\n"
"                           '+' - region was newly entered\n"
"                           '*' - region was not left\n"
"                           ' ' - region did not made any progress\n"
"  -Werror, --warnings-as-errors\n"
"                          all warnings are treated as errors\n"
"  -d, --debug             turn on debug mode\n"
"  -V, --version           print version information\n"
"  -h, --help              print this help information\n"
