    _e( END_OF_FUNCTION, "Unintentional reached end of function"),
    _e( INVALID_CALL, "Function call not allowed in current state"),
    _e( INVALID_ARGUMENT, "Parameter value out of range"),
    _e( INVALID_SIZE_GIVEN, "The given size cannot be used"),
    _e( UNKNOWN_TYPE, "The given type is not known"),
    _e( INTEGRITY_FAULT, "The structural integrity is not given"),
    _e( MEM_FAULT, "This could not be done with the given memory"),
    _e( MEM_ALLOC_FAILED, "Memory allocation failed"),
    _e( PROCESSED_WITH_FAULTS, "An error appeared when data was processed"),
    _e( INDEX_OUT_OF_BOUNDS, "Index out of bounds"),
    _e( F2C_INT_SIZE_MISMATCH, "Fortran and C integer size mismatch"),
    _e( UNKNOWN_REGION_TYPE, "Unknown region type"),
    _e( INVALID_LINENO, "Invalid source code line number"),
    _e( END_OF_BUFFER, "End of buffer/file reached"),
    _e( MPI_NO_WINDOW, "Cannot find MPI window"),
    _e( MPI_NO_COMM, "Cannot find MPI communicator"),
    _e( MPI_TOO_MANY_WINDOWS, "Too many MPI windows are created"),
    _e( MPI_TOO_MANY_COMMS, "Too many MPI communicators are created"),
    _e( MPI_TOO_MANY_GROUPS, "Too many MPI groups are created"),
    _e( MPI_NO_GROUP, "Cannot find MPI group"),
    _e( MPI_TOO_MANY_WINACCS, "Too many concurrent window accesses"),
    _e( MPI_NO_WINACC, "Cannot find window access entry"),
    _e( MPI_NO_LAST_REQUEST, "Missing termination in tracking data structure."),
    _e( USER_INVALID_REGION, "Usage of an invalid region handle"),
    _e( USER_INVALID_MGROUP, "Usage of an invalid metric group handle"),
    _e( FILE_INTERACTION, "Invalid file operation"),
    _e( FILE_CAN_NOT_OPEN, "Unable to open file"),
    _e( PARSE_UNKNOWN_TOKEN, "Error while parsing: Unknown token"),
    _e( PARSE_UNEXPECTED_END, "Error while parsing: Unexpected end of string"),
    _e( PARSE_NO_SEPARATOR, "Error while parsing: Missing seperator"),
    _e( PARSE_NO_KEY, "Error while parsing: Missing key"),
    _e( PARSE_NO_VALUE, "Error while parsing: Missing value"),
    _e( PARSE_INVALID_VALUE, "Error while parsing: Invalid value"),
    _e( PARSE_SYNTAX, "Error while parsing: Syntax error"),
    _e( POMP_SCL_BROKEN, "Expect location format 'filename:lineNo1:lineNo2'"),
    _e( POMP_UNKNOWN_SCHEDULE, "Unknown schedule specified"),
    _e( POMP_INVALID_SECNUM, "Invalid number of sections. Exspected > 0 sections"),
    _e( POMP_NO_NAME, "Name of user region missing"),
    _e( PROFILE_INCONSISTENT, "Inconsistent profile. Stop profiling"),
    _e( PROFILE_UNINITIALIZED_THREAD, "Profiling accessed uninitialized thread"),
    _e( PAPI_INIT, "Could not initialize PAPI library"),
    _e( MEMORY_OUT_OF_PAGES, "No free memory page available"),
    _e( SWITCH_IN_PARALLEL, "Switching recording on or off in a parallel region is not allowed. Please consult the manual for information, where recording can be switched on/off"),
    _e( OA_PARSE_MRI, "Could not parse MRI request"),
    _e( ON_SYSTEM_CALL, "Error in execution of system command"),
    _e( POMP_UNKNOWN_REGION_TYPE, "Unknown POMP region type specified in CTC string"),
    _e( DLOPEN_FAILED, "Cannot open library handle"),
    _e( DLSYM_FAILED, "Could not find symbol"),
    _e( DLCLOSE_FAILED, "Cannot close library handle"),
    _e( PERF_INIT, "An error occurred while initializing Linux PERF infrastructure"),
