TAUROOT=/Users/khuck/tau2
PERFDB_HOME=$(TAUROOT)/tools/src/perfdb

PACKAGES = \
	translator  \
	perfdb.util.io \
	perfdb.util.dbinterface \
	perfdb \
	perfdb.loadxml \
	perfdb.dbmanager \
	perfdb.configure \

JARS = \
	perfdb.jar \

JARS_3RDPARTY = \
	jargs.jar  \
	xerces.jar  \
	postgresql.jar \

MAIN_JAR     = perfdb.jar

RUN_PARAMETERS = 

include $(PERFDB_HOME)/make/Makefile

