PACKAGES = \
	translator  \
	perfdb.util.io \
	perfdb.util.dbinterface \
	perfdb \
	perfdb.loadxml \
	perfdb.analysisutil \
	perfdb.dbmanager \
	perfdb.configure \

JARS = \
	perfdb.jar  \

JARS_3RDPARTY = \
	xerces.jar  \
	postgresql.jar  \

MAIN_JAR     = perfdb.jar

RUN_PARAMETERS = 

include $(PERFDB_HOME)/make/Makefile

