#!/bin/bash

if [ $# -lt 1 ]
then
  echo ""
  echo "Usage: "
  echo ""
  echo "  $0 <path-to-TAU-data>"
  echo ""
  echo "Notes:"
  echo ""
  echo "  * Specify the file as either the path to the TAU profiles, or the"
  echo "    filename of the packed TAU data."
  echo ""
  exit 1
fi

working_path=`echo $0 | sed 's/doClasses//'`

eval perfexplorer -n -i ${working_path}classAggregation.py -p "tauData=$1"
