TAUROOT=
PERFDB_HOME=$(TAUROOT)/tools/src/perfdb

JAR_CONTENT = \
	perfdb \
	perfdb/configure \
	perfdb/loadxml \
	perfdb/util  \
	perfdb/util/rdb \
	perfdb/util/io  \
	perfdb/dbmanager \

include ${PERFDB_HOME}/make/Makefile
