include zerosum.mk

build/CMakeCache.txt:
	cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=$(CC) -DCMAKE_CXX_COMPILER=$(CXX) -DZeroSum_BUILD_TESTS=FALSE -DCMAKE_INSTALL_PREFIX=$(PREFIX)/$(TAUARCH) $(TAUOMPT) $(TAUCFLAGS) $(TAUCXXFLAGS) $(TAUCUDA) $(TAUHIP) $(TAUSYCL)

all : build/CMakeCache.txt
	$(MAKE) -C build all

install: all
	$(MAKE) -C build install

clean:
	rm -rf build

