'\" t
.\"     Title: TAU_PROFILER_GET_ExCLUSIVE_VALUES
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 04/15/2009
.\"    Manual: Tau API
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "TAU_PROFILER_GET_EXC" "3" "04/15/2009" "[FIXME: source]" "Tau API"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
TAU_PROFILER_GET_EXCLUSIVE_VALUES \- Returns the exclusive amount of a metric spend by this timer\&.
.SH "SYNOPSIS"
.sp
.ft B
.nf
C/C++:
.fi
.ft
.HP \w'TAU_PROFILER_GET_EXCLUSIVE_VALUES('u
.BI "TAU_PROFILER_GET_EXCLUSIVE_VALUES(Timer\ " "timer" ", double&\ " "excl" ");"
.SH "DESCRIPTION"
.PP
\fBTAU_PROFILER_GET_EXCLUSIVE_VALUES\fR
Returns the exclusive amount of the metric spend while this timer was running (and while no other subsequent timers was running\&.)
.SH "EXAMPLE"
.PP
>\fBC/C++:\fR
.sp
.if n \{\
.RS 4
.\}
.nf
void *ptr;
TAU_PROFILER_CREATE(ptr, "foo","", TAU_USER);

TAU_PROFILER_START(ptr);
foo(2);
TAU_PROFILER_STOP(ptr);

double excl[TAU_MAX_COUNTERS];
TAU_PROFILER_GET_EXCLUSIVE_VALUES(ptr, &excl); 
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP

TAU_PROFILER_CREATE
TAU_PROFILER_START
TAU_PROFILER_STOP
TAU_PROFILER_GET_CALLS
TAU_PROFILER_GET_CHILD_CALLS
TAU_PROFILER_GET_INCLUSIVE_VALUES
TAU_PROFILER_GET_COUNTER_INFO
