.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_INIT" "3" "08/31/2005" "" "TAU Instrumentation API"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
TAU_INIT \- Processes command\-line arguments for selective instrumentation
.SH "SYNOPSIS"
.PP
\fBC/C++:\fR
.HP 9
\fB\fBTAU_INIT\fR\fR\fB(\fR\fBint\ *\fR\fB\fIargc\fR\fR\fB, \fR\fBchar\ ***\fR\fB\fIargv\fR\fR\fB);\fR
.SH "DESCRIPTION"
.PP
TAU_INIT
parses and removes the command\-line arguments for the names of profile groups that are to be selectively enabled for instrumentation. By default, if this macro is not used, functions belonging to all profile groups are enabled.
TAU_INIT
differs from
TAU_PROFILE_INIT
only in the argument types.
.SH "EXAMPLE"
.PP
\fBC/C++ :\fR
.sp
.nf
int main(int argc, char **argv) {
  TAU_PROFILE("main()", "int (int, char **)", TAU_GROUP_12);
  TAU_INIT(&argc, &argv);
  ...
}

% ./a.out \-\-profile 12+14
    
.fi
.SH "SEE ALSO"
.PP
TAU_PROFILE_INIT(3)
