.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_DISABLE_CONTEXT_" "3" "08/31/2005" "" "TAU Instrumentation API"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
TAU_DISABLE_CONTEXT_EVENT \- Disable a context event
.SH "SYNOPSIS"
.PP
\fBC/C++:\fR
.HP 26
\fB\fBTAU_DISABLE_CONTEXT_EVENT\fR\fR\fB(\fR\fBTauUserEvent\ \fR\fB\fIevent\fR\fR\fB);\fR
.SH "DESCRIPTION"
.PP
Disables a context event.
.SH "EXAMPLE"
.PP
\fBC/C++ :\fR
.sp
.nf
int f2(void) {
  static int count = 0;
  count ++;
  TAU_PROFILE("f2()", "(sleeps 2 sec, calls f3)", TAU_USER);
  TAU_REGISTER_CONTEXT_EVENT(event, "Iteration count");

  if (count == 2)
    TAU_DISABLE_CONTEXT_EVENT(event);
  else
    TAU_ENABLE_CONTEXT_EVENT(event);

  printf("Inside f2: sleeps 2 sec, calls f3\\n");

  TAU_CONTEXT_EVENT(event, 232+count);
  sleep(2);
  f3();
  return 0;
}
    
.fi
.SH "SEE ALSO"
.PP
TAU_REGISTER_CONTEXT_EVENT(3),
TAU_ENABLE_CONTEXT_EVENT(3)
