.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_DUMP_FUNC_VALS_I" "3" "08/31/2005" "" "TAU Instrumentation API"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
TAU_DUMP_FUNC_VALS_INCR \- Dumps function values with a timestamp
.SH "SYNOPSIS"
.PP
\fBC/C++:\fR
.HP 24
\fB\fBTAU_DUMP_FUNC_VALS_INCR\fR\fR\fB(\fR\fBchar\ **\fR\fB\fIinFuncs\fR\fR\fB, \fR\fBint\ \fR\fB\fInumFuncs\fR\fR\fB);\fR
.SH "DESCRIPTION"
.PP
Similar to
TAU_DUMP_FUNC_VALS. This macro creates an incremental selective dump and dumps the results with a date stamp to the filename such as sel_dump__Thu\-Mar\-28\-16:30:48\-2002__.0.0.0. In this manner the previous
TAU_DUMP_FUNC_VALS_INCR(...)
are not overwritten (unless they occur within a second).
.SH "EXAMPLE"
.PP
\fBC/C++ :\fR
.sp
.nf
const char **inFuncs;
/* The first dimension is functions, and the second dimension is counters */
double **counterExclusiveValues;
double **counterInclusiveValues;
int *numOfCalls;
int *numOfSubRoutines;
const char **counterNames;
int numOfCouns;

TAU_GET_FUNC_VALS(inFuncs, 2,
  counterExclusiveValues,
  counterInclusiveValues,
  numOfCalls,
  numOfSubRoutines,
  counterNames,
  numOfCouns);

TAU_DUMP_FUNC_VALS(inFuncs, 2);
    
.fi
.SH "SEE ALSO"
.PP
TAU_DB_DUMP(3),
TAU_DUMP_FUNC_NAMES(3),
TAU_DUMP_FUNC_VALS(3)
