.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_PHASE" "3" "08/31/2005" "" "TAU Instrumentation API"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
TAU_PHASE \- Profile a C++ function as a phase
.SH "SYNOPSIS"
.HP 10
\fB\fBTAU_PHASE\fR\fR\fB(\fR\fBchar*\ or\ string&\ \fR\fB\fIfunction_name\fR\fR\fB, \fR\fBchar*\ or\ string&\ \fR\fB\fItype\fR\fR\fB, \fR\fBTauGroup_t\ \fR\fB\fIgroup\fR\fR\fB);\fR
.SH "DESCRIPTION"
.PP
\fBTAU_PHASE\fR
profiles a function as a phase. This macro defines the function and takes care of the timer start and stop as well. The timer will stop when the macro goes out of scope (as in C++ destruction).
.SH "EXAMPLE"
.sp
.nf
int foo(char *str) {
  TAU_PHASE(foo","int (char *)",TAU_DEFAULT);
  ...
}
    
.fi
.SH "SEE ALSO"
.PP
TAU_PHASE_CREATE_DYNAMIC(3),
TAU_PHASE_CREATE_STATIC(3)
