.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_DB_DUMP" "3" "08/31/2005" "" "TAU Instrumentation API"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
TAU_DB_DUMP \- Dumps the profile database to disk
.SH "SYNOPSIS"
.PP
\fBC/C++:\fR
.HP 12
\fB\fBTAU_DB_DUMP\fR\fR\fB(\fR\fBvoid);\fR
.PP
\fBFortran:\fR
.HP 12
\fB\fBTAU_DB_DUMP\fR\fR\fB(\fR\fBvoid);\fR
.SH "DESCRIPTION"
.PP
Dumps the profile database to disk. The format of the files is the same as regular profiles, they are simply prefixed with "dump" instead of "profile".
.SH "EXAMPLE"
.PP
\fBC/C++ :\fR
.sp
.nf
TAU_DB_DUMP();
    
.fi
.PP
\fBFortran :\fR
.sp
.nf
call TAU_DB_DUMP()
    
.fi
.SH "SEE ALSO"
.PP
TAU_DB_DUMP_PREFIX(3),
TAU_DB_DUMP_INCR(3),
TAU_DUMP_FUNC_NAMES(3),
TAU_DUMP_FUNC_VALS(3),
TAU_DUMP_FUNC_VALS_INCR(3),
TAU_DB_PURGE(3),
TAU_PROFILE_EXIT(3)
