.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_PHASE_CREATE_STA" "3" "08/31/2005" "" "TAU Instrumentation API"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
TAU_PHASE_CREATE_STATIC \- Defines a static phase.
.SH "SYNOPSIS"
.PP
\fBC/C++:\fR
.HP 24
\fB\fBTAU_PHASE_CREATE_STATIC\fR\fR\fB(\fR\fBPhase\ \fR\fB\fIphase\fR\fR\fB, \fR\fBchar*\ or\ string&\ \fR\fB\fIfunction_name\fR\fR\fB, \fR\fBchar*\ or\ string&\ \fR\fB\fItype\fR\fR\fB, \fR\fBTauGroup_t\ \fR\fB\fIgroup\fR\fR\fB);\fR
.PP
\fBFortran:\fR
.HP 24
\fB\fBTAU_PHASE_CREATE_STATIC\fR\fR\fB(\fR\fBinteger\ \fR\fB\fIphase\fR\fR\fB(2)\fR\fB, \fR\fBcharacter\ \fR\fB\fIname\fR\fR\fB(size)\fR\fB);\fR
.SH "DESCRIPTION"
.PP
TAU_PHASE_CREATE_STATIC
creates a static phase. Static phases (and timers) are more efficient than dynamic ones because the function registration only takes place once.
.SH "EXAMPLE"
.PP
\fBC/C++ :\fR
.sp
.nf
int f2(void)
{
  TAU_PHASE_CREATE_STATIC(t2,"IO Phase", "", TAU_USER);
  TAU_PHASE_START(t2);
  input();
  output();
  TAU_PHASE_STOP(t2);
  return 0;
}
.fi
.PP
\fBFortran :\fR
.sp
.nf
subroutine F2()

  integer phase(2) / 0, 0 /
  save    phase

  call TAU_PHASE_CREATE_STATIC(phase,'IO Phase')
  call TAU_PHASE_START(phase)

  call INPUT()
  call OUTPUT()

  call TAU_PHASE_STOP(phase)
end
.fi
.SH "SEE ALSO"
.PP
TAU_PHASE_CREATE_DYNAMIC(3),
TAU_PHASE_START(3),
TAU_PHASE_STOP(3)
