TAUROOT=
PERFDB_HOME=$(TAUROOT)/tools/src/perfdb

PACKAGE	= translator

SOURCE	= \
	GlobalThread.java \
	GlobalThreadDataElement.java \
	GlobalContext.java \
	GlobalNode.java  \
	GlobalMappingElement.java \
	GlobalMapping.java \
	Translator.java \

MAIN	= Translator

include ${PERFDB_HOME}/Makefile

