all:
	cd c; make clean; make
	cd cxx; make clean; make
	cd f90; make clean; make
run:
	cd c; make clean; make run
	cd cxx; make clean; make run
	cd f90; make clean; make run
clean:
	cd c; make clean
	cd cxx; make clean
	cd f90; make clean
