void shmem_addr_accessible_(void* addr, int* pe);
void shmem_barrier_(int* pestart, int* log_pestride, int* pesize, long* bar);
void shmem_barrier_all_(void);
void shmem_barrier_ps_(int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_broadcast32_(void* target, void* source, int* len, int* peroot, int* pestart, int* log_pestride,int* pesize, long* psync);
void shmem_broadcast4_(void* target, void* source, int* len, int* peroot, int* pestart, int* log_pestride,int* pesize, long* psync);
void shmem_broadcast64_(void* target, void* source, int* len, int* peroot, int* pestart, int* log_pestride,int* pesize, long* psync);
void shmem_broadcast8_(void* target, void* source, int* len, int* peroot, int* pestart, int* log_pestride,int* pesize, long* psync);
void shmem_character_get_(void* target, void* source, int* len, int* pe);
void shmem_character_put_(void* target, void* source, int* len, int* pe);
void shmem_clear_cache_inv_(void);
void shmem_clear_cache_line_inv_(void* target);
void shmem_clear_lock_(long* lock);
void shmem_collect4_(void* target, void* source, int* len, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_collect64_(void* target, void* source, int* len, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_collect8_(void* target, void* source, int* len, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_comp4_prod_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_comp4_sum_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_comp8_prod_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_comp8_sum_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_complex_get_(void* target, void* source, int* len, int* pe);
void shmem_complex_iget_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_complex_iput_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_complex_put_(void* target, void* source, int* len, int* pe);
void shmem_double_get_(void* target, void* source, int* len, int* pe);
void shmem_double_iget_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_double_iput_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_double_put_(void* target, void* source, int* len, int* pe);
void shmem_fcollect32_(void* target, void* source, int* nlong, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_fcollect4_(void* target, void* source, int* nlong, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_fcollect64_(void* target, void* source, int* nlong, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_fcollect8_(void* target, void* source, int* nlong, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_fence_(void);
void shmem_get128_(void* target, void* source, int* len, int* pe);
void shmem_get16_(void* target, void* source, int* len, int* pe);
void shmem_get32_(void* target, void* source, int* len, int* pe);
void shmem_get4_(void* target, void* source, int* len, int* pe);
void shmem_get64_(void* target, void* source, int* len, int* pe);
void shmem_get8_(void* target, void* source, int* len, int* pe);
void shmem_getmem_(void* target, void* source, int* len, int* pe);
/*
void shmem_group_create_strided_(int* pestart, int* pestride, int* pesize, int* racom, int* isync, int* handle);
void shmem_group_delete_(int* handle);
*/
void shmem_iget128_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget16_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget32_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget4_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget64_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget8_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_int2_and_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_max_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_min_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_or_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_prod_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_sum_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_xor_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_add_(void* target, int* value, int* pe);
void shmem_int4_and_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
int shmem_int4_cswap_(int* addr, int* match, int* value, int* pe);
int shmem_int4_fadd_(void* target, int* value, int* pe);
int shmem_int4_finc_(void* target,  int* pe);
void shmem_int4_inc_(void* target,  int* pe);
void shmem_int4_max_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_min_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_or_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_prod_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_sum_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
int  shmem_int4_swap_(void* target,int* value, int* pe);
void shmem_int4_wait_(int* var, int* value);
void shmem_int4_wait_until_(int* var, int* cond, int* value);
void shmem_int4_xor_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int8_add_(void* target, long* value, int* pe);
void shmem_int8_and_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
long shmem_int8_cswap_(long* addr, long*  match, long*  value, int* pe);
long shmem_int8_fadd_(void* target, int* value, int* pe);
long shmem_int8_finc_(void* target, int* pe);
void shmem_int8_inc_(void* target,  int* pe);
void shmem_int8_max_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_int8_min_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_int8_or_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_int8_prod_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_int8_sum_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
long shmem_int8_swap_(void* target,long* value, int* pe);
void shmem_int8_wait_(long* var, long* value);
void shmem_int8_wait_until_(long* var, int* cond, long* value);
void shmem_int8_xor_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_integer_get_(void* target, void* source, int* len, int* pe);
void shmem_integer_iget_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_integer_iput_(void* target, void* source, int* tst, int* sst, int* len, int*  pe);
void shmem_integer_put_(void* target, void* source, int* len, int* pe);
void shmem_iput128_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
/*
void shmem_iput16_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
*/
void shmem_iput32_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iput4_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iput64_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iput8_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_logical_get_(void* target, void* source, int* len, int* pe);
void shmem_logical_iget_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_logical_iput_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_logical_put_(void* target, void* source, int* len, int* pe);
int shmem_my_pe_(void);
int shmem_n_pes_(void);
int shmem_pe_accessible_(int* pe);
void shmem_ptr_(void* target, int* pe);
void shmem_put128_(void* target, void* source, int* len, int* pe);
/*
void shmem_put16_(void* target, void* source, int* len, int* pe);
*/
void shmem_put32_(void* target, void* source, int* len, int* pe);
void shmem_put4_(void* target, void* source, int* len, int* pe);
void shmem_put64_(void* target, void* source, int* len, int* pe);
void shmem_put8_(void* target, void* source, int* len, int* pe);
void shmem_putmem_(void* target, void* source, int* len, int* pe);
void shmem_quiet_(void);
void shmem_real16_max_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real16_min_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real16_prod_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real16_sum_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real4_max_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, float* pwrk, long* psync);
void shmem_real4_min_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, float* pwrk, long* psync);
void shmem_real4_prod_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, float* pwrk, long* psync);
void shmem_real4_sum_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, float* pwrk, long* psync);
float shmem_real4_swap_(void* target,float* value, int* pe);
void shmem_real8_max_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real8_min_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real8_prod_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real8_sum_to_all_(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
double shmem_real8_swap_(void* target,double* value, int* pe);
void shmem_real_get_(void* target, void* source, int* len, int* pe);
void shmem_real_iget_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_real_iput_(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_real_put_(void* target, void* source, int* len, int* pe);
void shmem_set_cache_inv_(void);
void shmem_set_cache_line_inv_(void* target);
void shmem_set_lock_(long* lock);
int shmem_swap_(void *target,int* value, int* pe);
int shmem_test_lock_(long* lock);
void shmem_udcflush_(void); 
void shmem_udcflush_line_(void* ptr);  
void shmem_wait_(long* var, long* value);
void shmem_wait_until_(int* var, int* cond, int* value);
void start_pes_(int *npes);
int shmem_my_pe_(void);
int shmem_n_pes_(void);

/* Duplicates with double underscores __ */

/*
void shmem_addr_accessible__(void* addr, int* pe);
void shmem_barrier__(int* pestart, int* log_pestride, int* pesize, long* bar);
void shmem_barrier_all__(void);
void shmem_barrier_ps__(int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_broadcast32__(void* target, void* source, int* len, int* peroot, int* pestart, int* log_pestride,int* pesize, long* psync);
void shmem_broadcast4__(void* target, void* source, int* len, int* peroot, int* pestart, int* log_pestride,int* pesize, long* psync);
void shmem_broadcast64__(void* target, void* source, int* len, int* peroot, int* pestart, int* log_pestride,int* pesize, long* psync);
void shmem_broadcast8__(void* target, void* source, int* len, int* peroot, int* pestart, int* log_pestride,int* pesize, long* psync);
void shmem_character_get__(void* target, void* source, int* len, int* pe);
void shmem_character_put__(void* target, void* source, int* len, int* pe);
void shmem_clear_cache_inv__(void);
void shmem_clear_cache_line_inv__(void* target);
void shmem_clear_lock__(long* lock);
void shmem_collect4__(void* target, void* source, int* len, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_collect64__(void* target, void* source, int* len, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_collect8__(void* target, void* source, int* len, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_comp4_prod_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_comp4_sum_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_comp8_prod_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_comp8_sum_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_complex_get__(void* target, void* source, int* len, int* pe);
void shmem_complex_iget__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_complex_iput__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_complex_put__(void* target, void* source, int* len, int* pe);
void shmem_double_get__(void* target, void* source, int* len, int* pe);
void shmem_double_iget__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_double_iput__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_double_put__(void* target, void* source, int* len, int* pe);
void shmem_fcollect32__(void* target, void* source, int* nlong, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_fcollect4__(void* target, void* source, int* nlong, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_fcollect64__(void* target, void* source, int* nlong, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_fcollect8__(void* target, void* source, int* nlong, int* pestart, int* log_pestride, int* pesize, long* psync);
void shmem_fence__(void);
void shmem_get128__(void* target, void* source, int* len, int* pe);
void shmem_get16__(void* target, void* source, int* len, int* pe);
void shmem_get32__(void* target, void* source, int* len, int* pe);
void shmem_get4__(void* target, void* source, int* len, int* pe);
void shmem_get64__(void* target, void* source, int* len, int* pe);
void shmem_get8__(void* target, void* source, int* len, int* pe);
void shmem_getmem__(void* target, void* source, int* len, int* pe);
void shmem_group_create_strided__(int* pestart, int* pestride, int* pesize, int* racom, int* isync, int* handle);
void shmem_group_delete__(int* handle);
void shmem_iget128__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget16__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget32__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget4__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget64__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iget8__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_int2_and_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_max_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_min_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_or_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_prod_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_sum_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int2_xor_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_add__(void* target, int* value, int* pe);
void shmem_int4_and_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
int shmem_int4_cswap__(int* addr, int* match, int* value, int* pe);
int shmem_int4_fadd__(void* target, int* value, int* pe);
int shmem_int4_finc__(void* target,  int* pe);
void shmem_int4_inc__(void* target,  int* pe);
void shmem_int4_max_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_min_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_or_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_prod_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int4_sum_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
int  shmem_int4_swap__(void* target,int* value, int* pe);
void shmem_int4_wait__(int* var, int* value);
void shmem_int4_wait_until__(int* var, int* cond, int* value);
void shmem_int4_xor_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, int* pwrk, long* psync);
void shmem_int8_add__(void* target, long* value, int* pe);
void shmem_int8_and_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
long shmem_int8_cswap__(long* addr, long*  match, long*  value, int* pe);
long shmem_int8_fadd__(void* target, int* value, int* pe);
long shmem_int8_finc__(void* target, int* pe);
void shmem_int8_inc__(void* target,  int* pe);
void shmem_int8_max_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_int8_min_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_int8_or_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_int8_prod_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_int8_sum_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
long shmem_int8_swap__(void* target,long* value, int* pe);
void shmem_int8_wait__(long* var, long* value);
void shmem_int8_wait_until__(long* var, int* cond, long* value);
void shmem_int8_xor_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, long* pwrk, long* psync);
void shmem_integer_get__(void* target, void* source, int* len, int* pe);
void shmem_integer_iget__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_integer_iput__(void* target, void* source, int* tst, int* sst, int* len, int*  pe);
void shmem_integer_put__(void* target, void* source, int* len, int* pe);
void shmem_iput128__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iput16__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iput32__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iput4__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iput64__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_iput8__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_logical_get__(void* target, void* source, int* len, int* pe);
void shmem_logical_iget__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_logical_iput__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_logical_put__(void* target, void* source, int* len, int* pe);
int shmem_my_pe__(void);
int shmem_n_pes__(void);
int shmem_pe_accessible__(int* pe);
void shmem_ptr__(void* target, int* pe);
void shmem_put128__(void* target, void* source, int* len, int* pe);
void shmem_put16__(void* target, void* source, int* len, int* pe);
void shmem_put32__(void* target, void* source, int* len, int* pe);
void shmem_put4__(void* target, void* source, int* len, int* pe);
void shmem_put64__(void* target, void* source, int* len, int* pe);
void shmem_put8__(void* target, void* source, int* len, int* pe);
void shmem_putmem__(void* target, void* source, int* len, int* pe);
void shmem_quiet__(void);
void shmem_real16_max_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real16_min_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real16_prod_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real16_sum_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real4_max_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, float* pwrk, long* psync);
void shmem_real4_min_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, float* pwrk, long* psync);
void shmem_real4_prod_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, float* pwrk, long* psync);
void shmem_real4_sum_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, float* pwrk, long* psync);
float shmem_real4_swap__(void* target,float* value, int* pe);
void shmem_real8_max_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real8_min_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real8_prod_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
void shmem_real8_sum_to_all__(void* target, void* source, int* nreduce, int* pestart, int* log_pestride, int* pesize, double* pwrk, long* psync);
double shmem_real8_swap__(void* target,double* value, int* pe);
void shmem_real_get__(void* target, void* source, int* len, int* pe);
void shmem_real_iget__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_real_iput__(void* target, void* source, int* tst, int* sst, int* len, int* pe);
void shmem_real_put__(void* target, void* source, int* len, int* pe);
void shmem_set_cache_inv__(void);
void shmem_set_cache_line_inv__(void* target);
void shmem_set_lock__(long* lock);
int shmem_swap__(void *target,int* value, int* pe);
int shmem_test_lock__(long* lock);
void shmem_udcflush__(void); 
void shmem_udcflush_line__(void* ptr);  
void shmem_wait__(long* var, long* value);
void shmem_wait_until__(int* var, int* cond, int* value);

void start_pes__(int *npes);
int shmem_my_pe__(void);
int shmem_n_pes__(void);


void shmem_clear_cache_inv(void);
void shmem_set_cache_inv(void);
void shmem_clear_cache_line_inv(void *target);
void shmem_set_cache_line_inv(void *target);
int my_pe_(void);
int my_pe__(void);
*/
/* And missing C symbols */

