include ../../../Makefile.inc

SOURCES = GetOpt.java \
	  BadOptException.java \
	  InstList.java \
	  InstListWriter.java

.PHONEY : default all clean

default : all

all : $(SOURCES)
	$(JAVAC) $(SOURCES)

clean :

