PACKAGE = perfdb.dbmanager

SOURCE  = \
	PartitionManager.java  \
	AppPartitionManager.java  \
	ExpPartitionManager.java  \
	TrialPartitionManager.java  \
	FunPartitionManager.java  \
	LocPartitionManager.java  \
	PprofPartitionManager.java  \
	TotalPartitionManager.java  \
	MeanPartitionManager.java  \
	UEPartitionManager.java  \

MAIN    = Main

include ${PERFDB_HOME}/make/Makefile
