TAUROOT=
PERFDB_HOME=$(TAUROOT)/tools/src/perfdb

PACKAGE = perfdb.loadxml

SOURCE  = \
	Load.java  \
	Main.java \
	LoadHandler.java \
	AppLoadHandler.java \

MAIN    = Main

include ${PERFDB_HOME}/Makefile
