TAUROOT=
PERFDB_HOME=$(TAUROOT)/tools/src/perfdb

PACKAGE = perfdb.configure

SOURCE  = \
	MaskingThread.java \
	PasswordField.java \
	Configure.java \

MAIN    = Configure

include $(PERFDB_HOME)/Makefile
