include ../../../Makefile.inc

SOURCES	= Message.java \
	  ErrorMessage.java \
	  WarningMessage.java \
	  MessageManager.java

.PHONEY : default all clean clean-emacs

default : all

all : $(SOURCES)
	$(JAVAC) $(SOURCES)

clean :

