#!/bin/sh

#############################################################################
# checkExtraRTS script for pC++/Sage++
# This script checks for installed pC++ runtime systems
#
# Usage: checkExtraRTS <sageroot-path> <machine-type>
#
# Bernd Mohr 3/2/95
#############################################################################

# -- change directory to SAGEROOT, so paths are interpreted correctly
cd $1

arch=$2
rts=""

# -- check for Awesime runtime system
if [ -r target/awe-ms/lib/libpcxx.a ]
then
	rts="$rts awe-ms"
fi

# -- check for Sun's LWP runtime system
if [ -r target/lwp-ms/lib/libpcxx.a ]
then
	rts="$rts lwp-ms"
fi

# -- check for POSIX threads runtime system
if [ -r target/pthread-ms/lib/${arch}/libpcxx.a ]
then
	rts="$rts pthread-ms"
fi

# -- check for AT&T task library runtime system
if [ -r target/task-ms/lib/${arch}/libpcxx.a ]
then
	rts="$rts task-ms"
fi

# -- check for PVM runtime systems
if [ -f $PVM_ROOT/include/pvm3.h ]
then
	eval `grep '^PVM_ARCH' target/pvm/src/Makefile`
	if [ -r target/pvm/lib/$PVM_ARCH/libpcxx.a ]
	then
		rts="$rts pvmexe"
	fi
	if [ -r tulip/pvm/lib/$PVM_ARCH/libpcxx.a ]
	then
		rts="$rts pvmNEW"
	fi
fi

# -- check for MPI runtime systems
if [ -r $MPI_DIR/include/mpi.h ]
then
	eval `grep '^MPI_ARCH' target/mpi/src/Makefile`
	if [ -r target/mpi/lib/$MPI_ARCH/libpcxx.a ]
	then
		rts="$rts mpi"
	fi
	if [ -r tulip/mpi/lib/${arch}/libpcxx.a ]
	then
		rts="$rts mpiNEW"
	fi
fi

echo $rts
