##########################
#Author: Robert Bell.

#Makefile that makes all the components of ParaProf.
#The resulting ParaProf.jar file is placed in the ./bin
#directory.
##########################

default: ParaProf

ParaProf:
	cd src/edu/uoregon/tau/paraprof/; make

clean:
	cd src; make clean
	rm -f ./bin/ParaProf.jar

