TAUROOT=
PERFDB_HOME=$(TAUROOT)/tools/src/perfdb

PACKAGE = perfdb.util.dbinterface

SOURCE  = \
	JDBCAcct.java  \
	DBAcct.java  \
	DBConnector.java  \
	DB.java \
	ParseConfig.java \

include ${PERFDB_HOME}/Makefile
