#!/bin/bash

if [ $# -lt 1 ] ; then
  echo ""
  echo "Usage: "
  echo ""
  echo "  $0 <testingData.csv>"
  echo ""
  echo "Notes:"
  echo ""
  echo "  none."
  echo ""
  exit 1
fi

verbose="no"
if [ $# -eq 2 ] ; then
  verbose="yes"
fi

working_path=`echo $0 | sed 's/runit//'`
rules="${working_path}CPI-stack.drl"

eval perfexplorer -c NO_DATABASE -n -i ${working_path}processCPI.py -p "inputData=$1,rules=$rules,verbose=$verbose"
