.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "PARAPROF" "1" "12/12/2008" "" "Tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
paraprof \- Launches TAU's Java\-based performance data viewer.
.SH "SYNOPSIS"
.HP 9
\fBparaprof\fR [\-h,\ \-\-help] [\-f,\ \-\-filetype\ \fIfiletype\fR] [\-\-pack\ \fIfile\fR] [\-\-dump] [\-o,\ \-\-oss] [\-s,\ \-\-summary]
.SH "NOTES"
.PP
For the TAU profiles type, you can specify either a specific set of profile files on the commandline, or you can specify a directory (by default the current directory). The specified directory will be searched for profile.*.*.* files, or, in the case of multiple counters, directories named MULTI_* containing profile data.
.SH "OPTIONS"
.TP
\fB\-h\fR
Display help
.TP
\fB\-f, \-\-filetype \fR\fB\fIfiletype\fR\fR
Specify type of performance data. Options are: profiles (default), pprof, dynaprof, mpip, gprof, psrun, hpm, packed, cube, hpc, ompp, snap, perixml, gptl
.TP
\fB\-\-pack \fR\fB\fIfile\fR\fR
Pack the data into packed (.ppk) format (does not launch ParaProf GUI)
.TP
\fB\-\-dump\fR
Dump profile data to TAU profile format (does not launch ParaProf GUI).
.TP
\fB\-o, \-\-oss\fR
Print profile data in OSS style text output
.TP
\fB\-s, \-\-summary\fR
Print only summary statistics (only applies to OSS output)
.SH "DOCUMENTATION"
.PP
Complete documentation can be found at
\fIhttp://www.cs.uoregon.edu/research/tau/tau\-usersguide.pdf\fR
