.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "PERFEXPLORER_CONFIGU" "1" "04/25/2011" "" "Tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
perfexplorer_configure \- Configures a perfdmf database for use with perfexplorer.
.SH "SYNOPSIS"
.HP 23
\fBperfexplorer_configure\fR
.SH "DESCRIPTION"
.PP
Configures a perfdmf database for use with perfexplorer.
