.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "PERFDMF_CREATEEXP" "1" "06/04/2008" "" "Tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
perfdmf_createexp \- Command line tool to create a experiment in the perfdmf database.
.SH "SYNOPSIS"
.HP 18
\fBperfdmf_createexp\fR [\-h,\ \-\-help] [\-g,\ \-\-configFile\ \fIconfigFile\fR] [\-c,\ \-\-config\ \fIconfiguration_name\fR] {\-a,\ \-\-applicationid\ \fIapplicationID\fR} {\-n,\ \-\-name\ \fIname\fR}
.SH "DESCRIPTION"
.PP
This script will create a new experiment in the perfdmf database.
.SH "OPTIONS"
.PP
\-g, \-\-configFile
\fIconfigFile \fR
specify the path to the file that defines the perfdmf configuration.
.PP
\-c, \-\-config
\fIconfiguration_name \fR
specify the name of the perfdmf configuration \-c foo is equalivent to \-g <home>/.ParaProf/perfdmf.cfg.foo.
.PP
\-a, \-\-applicationid
\fIapplicationID \fR
specify the id number of the application to associate with the new experiment.
.PP
\-n, \-\-name
\fIname \fR
the name of the application.
