.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_TIMECORRECT" "1" "12/12/2008" "" "Tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
tau_timecorrect \- Corrects and reorders the records of tau trace files.
.SH "SYNOPSIS"
.HP 16
\fBtau_timecorrect\fR {\fItrace\ input\ file\fR} {\fIEDF\ input\ file\fR} {\fItrace\ output\ file\fR} {\fIEDF\ input\ file\fR}
.SH "DESCRIPTION"
.PP
This program takes in tau trace files, reorders and corrects the times of these records and then outputs the records to new trace files. The time correction algorithm uses a logical clock algorithm with amortization. This is done by adjusting the times of events such that the product of an effect happens after the cause of that effect.
.SH "OPTIONS"
.PP
\fBtrace input file\fR
.PP
\fBEDF input file\fR
.PP
\fBtrace output file\fR
.PP
\fBEDF output file\fR
