.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_THROTTLE.SH" "1" "07/06/2007" "" "Tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
tau_throttle.sh \- This tool generates a selective instrumentation file (called throttle.tau) from a program output that has "Disabling" messages.
.SH "SYNOPSIS"
.HP 16
\fBtau_throttle.sh\fR
.SH "DESCRIPTION"
.PP
This tools will auto\-generates a selective instrumenation file basied on output from a program that has the profiling of some its functions throttled.
