.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "TAU_SETUP" "1" "08/11/2008" "" "Tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
tau_setup \- Launches GUI interface to configure TAU.
.SH "SYNOPSIS"
.HP 10
\fBtau_setup\fR
.SH "OPTIONS"
.PP
\-v Verbose output.
.PP
\-\-html Output results in HTML.
.PP
\-\-build Only build.
.PP
\-\-run Only run.
