.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "VTFCONVERTER" "1" "12/12/2008" "" "Tools"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vtfconverter \- 
.SH "SYNOPSIS"
.HP 13
\fBvtfconverter\fR [\-h] [\-c] [\-f\ \fIfile\fR] [\-p\ \fIpath\fR] [\-i\ \fIfrom\fR\ \fIto\fR]
.SH "DESCRIPTION"
.PP
Converts VTF profile to TAU profiles and launches an interactive VTF prompt.
.SH "OPTIONS"
.PP
\-c Opens command line interface.
.PP
\-f Converts trace [file] to TAU profiles.
.PP
\-p Places the resulting profiles in the directory [path].
.PP
\-i States that the interval [from],[to] should be profiled.
