#!/bin/sh

PERFDB_JAR=${PERFDB_HOME}/jars/perfdb.jar
XMLSAX_JAR=${PERFDB_HOME}/jars/xerces.jar
JDBC_JAR=${PERFDB_HOME}/jars/postgresql.jar
DMS_JAR=dms.jar

java -cp ./examples:${DMS_JAR}:${PERFDB_JAR}:${XMLSAX_JAR}:${JDBC_JAR} SimpleExample ${PERFDB_HOME}/data/perfdb.cfg

JDBC_JAR=${PERFDB_HOME}/jars/mysql.jar

java -cp ./examples:${DMS_JAR}:${PERFDB_JAR}:${XMLSAX_JAR}:${JDBC_JAR} SimpleExample ${PERFDB_HOME}/data/perfdb.cfg.mysql
