#!/bin/sh
#
# A simple filter for hpcxx2dep that outputs the information requested
# by the dump flag.
#
# Kurt Windisch 12/12/96

# Removed the command to get rid of blank lines (Kurt 4/1/97): -e '/^ *$/d'

if [ $# -ne 2 ]
then
  echo "usage: $0 [ -dumpcg | -dumpall | -dumptxt | -dumpch | -dumpbdb] depfile"
  exit 1
fi

case $2 in
*.dep)
	case $1 in
	-dumpcg)
		sed -e '/^#/d' -e '/^fpos/d' \
                    -e '/^ctag/d' -e '/^cfile/d' -e '/^csub/d' -e '/^cmem/d' \
                    -e '/^cpos/d' -e '/^cmpos/d' -e '/^cbase/d' \
                    -e 's/ @.*$//' $2 
		;;
	-dumpall)
		sed -e 's/^#//' -e '/^fpos/d' -e '/^fline/d' \
                    -e '/^ctag/d' -e '/^cfile/d' -e '/^csub/d' -e '/^cmem/d' \
                    -e '/^cpos/d' -e '/^cmpos/d' -e '/^cbase/d' \
                    -e 's/ @.*$//' $2
		;;
        -dumpbdb)
		sed -e '/^#/d' -e '/^fcalls/d' -e '/^fpos/d' -e '/^fline/d' \
                    -e '/^fclass/d' -e '/^csub/d' -e '/^cmem/d' \
                    -e '/^cbase/d' -e '/^cpos/d' -e '/^cmpos/d' \
                    -e '/^ftype: [a-zA-z0-9]\+ Mem/d' \
                    -e '/^ftype: [a-zA-z0-9]\+ Ord/d' \
                    -e 's/ @.*$//' $2
		;;
	-dumptxt)
		sed -e '/^#/d' -e '/^fline/d' -e '/^csub/d' -e '/^cmem/d' \
		     $2
		;;
	-dumpch)
		sed -e '/^#/d' -e '/^ftag/d' -e '/^ffile/d' -e '/^fpos/d' \
                    -e '/^fline/d' -e '/^fcalls/d' -e '/^fclass/d' \
                    -e '/^ftype/d' -e '/^cfile/d' -e '/^cbase/d' \
                    -e '/^cpos/d' -e '/^cmpos/d' \
                    -e '/^[0-9]\+/d' -e 's/ @.*$//' $2
		;;
	*)
		echo "$0: unknown option $1"
		exit 1
		;;
	esac
	;;
*)
	echo "$2: not a valid HPC++ depfile"
	exit 1
	;;
esac
exit 0
