include ../../../Makefile.inc

SOURCES	= Interpreter.java \
	  DataSource.java \
	  ProfileDataSource.java

.PHONEY : default all clean

default : all

all : $(SOURCES)
	$(JAVAC) $(SOURCES)

clean :

